name: Publish Docker image
on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        run: |
          docker build -t  pnp-powershell .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker images
          #docker tag pnp-powershell kuzhel/pnp-powershell:latest
          #docker push kuzhel/pnp-powershell:latest
